---
services:
  loadmonitor:
    build: ./
    ports:
      - 8085:8085
      - 8081:8081
    environment:
      - CONFIG_PATH=config/local.yaml

  prometheus: 
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
    # mapping local promconfig to inner prometheus yml config
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=someThing_321
    volumes:
    # here is yaml NOT yml !! in the container
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana


volumes:
  grafana:
