---
services:
  loadmonitor:
    build: ./
    ports:
      - 8085:8085
      - 8081:8081

  prometheus: 
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
    # mapping local promconfig to inner prometheus yml config
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml