global:
# low values for debug only.. prod 15? 30?
  scrape_interval: 5s 
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: loadmonitor
  static_configs: 
    - targets: ["loadmonitor:8081"]